export const APP_TEXTS = {
  app: {
    name: "Yeshiva Clicker",
    hello: "שלום",
    installApp: "התקן אפליקציה",
    logout: "התנתק",
    installInstructions: "כדי להתקין כאפליקציה:\nבמחשב (Chrome): לחץ על סמל ההתקנה בשורת הכתובת.\nבטלפון (Safari/Chrome): בחר ב'הוסף למסך הבית' מתפריט השיתוף/הגדרות.",
  },
  tabs: {
    clicker: "מונה לחיצות",
    map: "מפת לחיצות",
    leaderboard: "טבלת מובילים",
    admin: "ניהול",
  },
  clicker: {
    title: "מונה לחיצות",
    clickHere: "לחץ כאן!",
    locationNote: "* הלחיצה תשמור את המיקום שלך (אם תאשר)",
  },
  leaderboard: {
    title: "טבלת מובילים",
    empty: "אין עדיין משתמשים שלחצו",
  },
  map: {
    totalClicks: "סך הכל לחיצות:",
  },
  admin: {
    title: "ניהול משתמשים",
    yeshivasTitle: "ניהול ישיבות",
    addYeshiva: "הוסף ישיבה",
    addYeshivaPlaceholder: "שם הישיבה...",
    totalUsers: "סה״כ משתמשים:",
    columns: {
      name: "שם",
      yeshiva: "ישיבה",
      email: "אימייל",
      status: "סטטוס",
      actions: "פעולות",
    },
    status: {
      pending: "ממתין",
      approved: "מאושר",
      rejected: "נדחה",
    },
    actions: {
      approve: "אשר",
      reject: "דחה",
      delete: "מחק",
      confirmDelete: "האם אתה בטוח שברצונך למחוק את המשתמש",
      addClick: "הוסף לחיצה",
      removeClick: "הורד לחיצה",
    },
  },
  auth: {
    loginTitle: "התחברות",
    loginSubtitle: "הזן את פרטיך כדי להתחבר למערכת",
    registerTitle: "הרשמה",
    registerSubtitle: "צור חשבון חדש במערכת",
    email: "דוא\"ל",
    password: "סיסמה",
    fullName: "שם מלא",
    yeshiva: "ישיבה",
    selectYeshiva: "בחר ישיבה...",
    loginBtn: "התחבר",
    loginBtnLoading: "מתחבר...",
    registerBtn: "הירשם",
    registerBtnLoading: "נרשם...",
    noAccount: "אין לך חשבון?",
    registerHere: "הירשם כאן",
    hasAccount: "יש לך כבר חשבון?",
    loginHere: "התחבר",
    waitingTitle: "ממתין לאישור",
    waitingMessage: "החשבון שלך נוצר בהצלחה. אנא המתן עד שמנהל המערכת יאשר את חשבונך.",
    rejectedTitle: "החשבון שלך נדחה.",
    loading: "טוען...",
    missingDataTitle: "שגיאה: נתוני המשתמש חסרים",
    missingDataDesc1: "החשבון שלך נוצר במערכת ההזדהות (Auth), אך נתוניו לא נשמרו במסד הנתונים (Firestore).",
    missingDataDesc2: "זה קורה בדרך כלל בגלל שחוקי האבטחה (Security Rules) ב-Firebase חוסמים כתיבה.",
    logoutAndRetry: "התנתק ונסה שוב",
    changePassword: "שינוי סיסמה",
    changePasswordDescription: "כדי לשמור על אבטחת חשבונך, עליך להזין את הסיסמה הנוכחית לפני קביעת סיסמה חדשה.",
    currentPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmNewPassword: "אימות סיסמה חדשה",
    changePasswordBtn: "עדכן סיסמה",
    changePasswordSuccess: "הסיסמה עודכנה בהצלחה",
    passwordsDontMatch: "הסיסמאות החדשות אינן תואמות",
    wrongCurrentPassword: "הסיסמה הנוכחית אינה נכונה",
  },
  contact: {
    whatsappNumber: "972500000000",
    whatsappMessage: "שלום, אני פונה מהאפליקציה...",
  }
};
