export const APP_TEXTS = {
  app: {
    name: "Yeshiva Clicker",
    hello: "שלום",
    installApp: "התקנת אפליקציה",
    logout: "יציאה",
    installInstructions: "כדי להתקין כאפליקציה:\nבמחשב (Chrome): יש ללחוץ על סמל ההתקנה בשורת הכתובת.\nבטלפון (Safari/Chrome): יש לבחור ב'הוסף למסך הבית' מתפריט השיתוף/הגדרות.",
  },
  tabs: {
    clicker: "מונה לחיצות",
    map: "מפת לחיצות",
    leaderboard: "טבלת מובילים",
    admin: "ניהול",
  },
  clicker: {
    title: "מונה לחיצות",
    clickHere: "לחצו כאן!",
    locationNote: "* הלחיצה תשמור את המיקום (אם תאשרו גישה)",
  },
  leaderboard: {
    title: "טבלת מובילים",
    empty: "אין עדיין משתמשים שלחצו",
  },
  map: {
    totalClicks: "סך הכל לחיצות:",
  },
  admin: {
    title: "ניהול משתמשים",
    yeshivasTitle: "ניהול מוסדות",
    addYeshiva: "הוספת מוסד",
    addYeshivaPlaceholder: "שם המוסד...",
    totalUsers: "סה״כ משתמשים:",
    columns: {
      name: "שם",
      yeshiva: "מוסד",
      email: "אימייל",
      status: "סטטוס",
      actions: "פעולות",
    },
    status: {
      pending: "בהמתנה",
      approved: "מאושר/ת",
      rejected: "נדחה",
    },
    actions: {
      approve: "אישור",
      reject: "דחייה",
      delete: "מחיקה",
      confirmDelete: "האם למחוק את המשתמש:",
      addClick: "הוספת לחיצה",
      removeClick: "הורדת לחיצה",
    },
  },
  auth: {
    loginTitle: "כניסה",
    loginSubtitle: "הזינו פרטים כדי להיכנס למערכת",
    registerTitle: "הרשמה",
    registerSubtitle: "יצירת חשבון חדש במערכת",
    email: "דוא\"ל",
    password: "סיסמה",
    fullName: "שם מלא",
    yeshiva: "ישיבה",
    selectYeshiva: "בחרו ישיבה...",
    loginBtn: "כניסה",
    loginBtnLoading: "בתהליך התחברות...",
    registerBtn: "הרשמה",
    registerBtnLoading: "בתהליך הרשמה...",
    noAccount: "עדיין אין לך חשבון?",
    registerHere: "להרשמה",
    hasAccount: "יש לך כבר חשבון?",
    loginHere: "לכניסה",
    waitingTitle: "בהמתנה לאישור",
    waitingMessage: "החשבון נוצר בהצלחה. יש להמתין עד שמנהל המערכת יאשר את החשבון.",
    rejectedTitle: "החשבון נדחה.",
    loading: "טוען...",
    missingDataTitle: "שגיאה: נתוני המשתמש חסרים",
    missingDataDesc1: "החשבון נוצר במערכת ההזדהות (Auth), אך נתוניו לא נשמרו במסד הנתונים (Firestore).",
    missingDataDesc2: "זה קורה בדרך כלל בגלל שחוקי האבטחה (Security Rules) ב-Firebase חוסמים כתיבה.",
    logoutAndRetry: "יציאה וניסיון חוזר",
    changePassword: "שינוי סיסמה",
    changePasswordDescription: "כדי לשמור על אבטחת חשבונכם, יש להזין סיסמה נוכחית לפני קביעת סיסמה חדשה.",
    currentPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmNewPassword: "אימות סיסמה חדשה",
    changePasswordBtn: "עדכון סיסמה",
    changePasswordSuccess: "הסיסמה עודכנה בהצלחה",
    passwordsDontMatch: "הסיסמאות החדשות אינן תואמות",
    wrongCurrentPassword: "הסיסמה הנוכחית שגויה",
  },
  contact: {
    whatsappNumber: "972500000000",
    whatsappMessage: "שלום, אני פונה מהאפליקציה...",
  }
};
