export const APP_TEXTS = {
  app: {
    name: "Yeshiva Clicker",
    hello: "שלום",
    installApp: "התקנת אפליקציה",
    logout: "יציאה",
    installInstructions: "כדי להתקין כאפליקציה:\nבמחשב (Chrome): יש ללחוץ על סמל ההתקנה בשורת הכתובת.\nבטלפון (Safari/Chrome): יש לבחור ב'הוסף למסך הבית' מתפריט השיתוף/הגדרות.",
  },
  tabs: {
    clicker: "מונה לחיצות",
    map: "מפת לחיצות",
    myclicks: "הלחיצות שלי",
    leaderboard: "טבלת מובילים",
    admin: "ניהול",
  },
  clicker: {
    title: "מונה לחיצות",
    clickHere: "לחצו כאן!",
    locationNote: "* הלחיצה תשמור את המיקום (אם תאשרו גישה)",
  },
  leaderboard: {
    title: "טבלת מובילים",
    empty: "אין עדיין משתמשים שלחצו",
  },
  map: {
    totalClicks: "סך הכל לחיצות:",
  },
  myclicks: {
    title: "הלחיצות שלי",
    showOnMap: "הצג במפה",
    delete: "מחיקה",
    empty: "אין היסטורית לחיצות",
    emptyDesc: "עדיין לא נרשמו לחיצות עם מיקום מוגדר.",
  },
  dashboard: {
    personalSettings: "הגדרות אישיות",
    chat: "צ'אט",
    defaultScreenTitle: "בחירת מסך ברירת מחדל:",
    defaultScreenDesc: "מסך זה יוצג אוטומטית בכל כניסה לאפליקציה.",
    tefillin: "תפילין",
    shabbatCandles: "נרות שבת",
    other: "אחר",
    close: "סגור"
  },
  admin: {
    title: "ניהול משתמשים",
    yeshivasTitle: "ניהול מוסדות (בנים)",
    ulpanasTitle: "ניהול מוסדות (בנות)",
    addYeshiva: "הוספת ישיבה",
    addUlpana: "הוספת אולפנה",
    addYeshivaPlaceholder: "שם המוסד...",
    noYeshivas: "אין ישיבות במערכת.",
    noUlpanas: "אין אולפנות במערכת.",
    deleteYeshiva: "מחק ישיבה",
    deleteUlpana: "מחק אולפנה",
    totalUsers: "סה״כ משתמשים:",
    tabs: {
      users: "משתמשים",
      institutions: "ניהול מוסדות",
      settings: "הגדרות אתר"
    },
    settings: {
      title: "הגדרות אתר",
      save: "שמור שינויים",
      saving: "שומר...",
      saveSuccess: "נשמר בהצלחה!",
      general: "מאפיינים כלליים",
      defaultScreen: "מסך ברירת מחדל",
      defaultScreenDesc: "בחר את המצב שיוצג למשתמשים בפעם הראשונה שהם נכנסים.",
      design: "עיצוב וצבעים",
      primaryColor: "צבע ראשי",
      secondaryColor: "צבע משני",
      backgroundColor: "צבע רקע",
      logo: "לוגו האתר",
      uploadLogo: "העלה",
      uploading: "מעלה...",
      removeLogo: "הסר לוגו",
      preview: "תצוגה מקדימה",
      primaryBtn: "כפתור ראשי",
      secondaryBtn: "כפתור משני",
      textsTitle: "טקסטים באתר",
      tefillin: "תפילין",
      shabbatCandles: "נרות שבת"
    },
    columns: {
      name: "שם",
      yeshiva: "מוסד",
      email: "אימייל",
      status: "סטטוס",
      actions: "פעולות",
    },
    status: {
      pending: "בהמתנה",
      approved: "מאושר/ת",
      rejected: "נדחה",
    },
    actions: {
      approve: "אישור",
      reject: "דחייה",
      delete: "מחיקה",
      confirmDelete: "האם למחוק את המשתמש:",
      addClick: "הוספת לחיצה",
      removeClick: "הורדת לחיצה",
      save: "שמור",
      edit: "ערוך"
    },
    userFields: {
      gender: "מין",
      phone: "טלפון",
      role: "תפקיד",
      boy: "בן",
      girl: "בת",
      user: "משתמש",
      admin: "מנהל",
      selectInstitution: "בחר מוסד...",
      yeshivas: "ישיבות",
      ulpanas: "אולפנות",
      tefillin: "תפילין",
      candles: "נרות שבת",
      other: "אחר"
    }
  },
  auth: {
    loginTitle: "כניסה",
    loginSubtitle: "הזינו פרטים כדי להיכנס למערכת",
    registerTitle: "הרשמה",
    registerSubtitle: "יצירת חשבון חדש במערכת",
    email: "דוא\"ל",
    password: "סיסמה",
    fullName: "שם מלא",
    yeshiva: "ישיבה",
    selectYeshiva: "בחרו ישיבה...",
    ulpana: "אולפנה",
    selectUlpana: "בחרו אולפנה...",
    selectInstitution: "בחרו מוסד...",
    loginBtn: "כניסה",
    loginBtnLoading: "בתהליך התחברות...",
    registerBtn: "הרשמה",
    registerBtnLoading: "בתהליך הרשמה...",
    noAccount: "עדיין אין לך חשבון?",
    registerHere: "להרשמה",
    hasAccount: "יש לך כבר חשבון?",
    loginHere: "לכניסה",
    waitingTitle: "בהמתנה לאישור",
    waitingMessage: "החשבון נוצר בהצלחה. יש להמתין עד שמנהל המערכת יאשר את החשבון.",
    rejectedTitle: "החשבון נדחה.",
    loading: "טוען...",
    missingDataTitle: "שגיאה: נתוני המשתמש חסרים",
    missingDataDesc1: "החשבון נוצר במערכת ההזדהות (Auth), אך נתוניו לא נשמרו במסד הנתונים (Firestore).",
    missingDataDesc2: "זה קורה בדרך כלל בגלל שחוקי האבטחה (Security Rules) ב-Firebase חוסמים כתיבה.",
    logoutAndRetry: "יציאה וניסיון חוזר",
    changePassword: "שינוי סיסמה",
    changePasswordDescription: "כדי לשמור על אבטחת חשבונכם, יש להזין סיסמה נוכחית לפני קביעת סיסמה חדשה.",
    currentPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmNewPassword: "אימות סיסמה חדשה",
    changePasswordBtn: "עדכון סיסמה",
    changePasswordSuccess: "הסיסמה עודכנה בהצלחה",
    passwordsDontMatch: "הסיסמאות החדשות אינן תואמות",
    wrongCurrentPassword: "הסיסמה הנוכחית שגויה",
    
    // New text values for register
    genderSelectTitle: "נא לבחור מין (בן / בת)",
    boy: "בן",
    girl: "בת",
    invalidPhone: "נא להזין מספר טלפון תקין (9 או 10 ספרות, מתחיל ב-0)",
    invalidEmail: "נא להזין כתובת דוא״ל תקינה",
    profileCompleteTitle: "השלמת הרשמה",
    profileCompleteDesc: "אנא השלם את פרטי הפרופיל שלך",
    iAm: "אני:",
    whatsappAddInstitutionHelp: "היי, אשמח שתוסיפו את המוסד שלי לרשימה:",
    whatsappAddInstitutionLink: "לא מוצאים? שלחו לנו בווצאפ ונוסיף",
    phoneInput: "מספר טלפון",
    emailInput: "כתובת מייל"
  },
  contact: {
    whatsappNumber: "972500000000",
    whatsappMessage: "שלום, אני פונה מהאפליקציה...",
  }
};
